const API_VERSION='2026-03-10';
const SETTINGS='site/data/settings.json',PRESETS='site/data/presets.json',INDEX='portfolio/index.json';
const enc=new TextEncoder(),dec=new TextDecoder();
export default {async fetch(req,env){try{if(req.method==='OPTIONS')return cors(new Response(null,{status:204}),req,env);const u=new URL(req.url),p=u.pathname;
if(p==='/health')return cors(json({ok:true,version:'1.0.0'}),req,env);
if(p==='/auth/login'&&req.method==='POST')return passwordLogin(req,env);if(p==='/auth/logout'&&req.method==='POST')return logout(req,env);
if(p==='/api/public/settings')return cors(json({settings:await publicJson(env,SETTINGS)}),req,env);
if(p==='/api/public/portfolio')return cors(await publicPortfolio(u,env),req,env);
if(p==='/api/public/presets')return cors(await publicPresets(u,env),req,env);
if(p.startsWith('/media/'))return cors(await media(p.slice(7),env),req,env);
if(p.startsWith('/api/admin/')){const s=await session(req,env);if(!s)return cors(json({error:'로그인이 필요합니다.'},401),req,env);
if(p==='/api/admin/session')return cors(json({user:{login:s.login,avatar:s.avatar||''}}),req,env);
if(p==='/api/admin/settings'&&req.method==='GET')return cors(json({settings:await ghJson(env,s.token,SETTINGS)}),req,env);
if(p==='/api/admin/settings'&&req.method==='PUT')return cors(await saveSettings(req,env,s),req,env);
if(p==='/api/admin/portfolio'&&req.method==='GET')return cors(json({items:await adminPortfolio(env,s.token)}),req,env);
if(p==='/api/admin/presets'&&req.method==='GET')return cors(json({items:await ghJson(env,s.token,PRESETS).catch(()=>[])}),req,env);
if(p==='/api/admin/upload'&&req.method==='POST')return cors(await upload(req,env,s,false),req,env);
if(p==='/api/admin/preset-upload'&&req.method==='POST')return cors(await upload(req,env,s,true),req,env);
if(p==='/api/admin/delete'&&req.method==='POST')return cors(await del(req,env,s,false),req,env);
if(p==='/api/admin/site-image'&&req.method==='POST')return cors(await siteImage(req,env,s),req,env);
if(p==='/api/admin/site-image/delete'&&req.method==='POST')return cors(await siteImageDelete(req,env,s),req,env);
if(p==='/api/admin/preset-delete'&&req.method==='POST')return cors(await del(req,env,s,true),req,env);
}
return cors(json({error:'Not found'},404),req,env)}catch(e){console.error(e);return cors(json({error:env.DEBUG==='true'?String(e.message||e):'서버 처리 중 오류가 발생했습니다.'},500),req,env)}}};
function json(x,status=200,extra={}){return new Response(JSON.stringify(x),{status,headers:{'Content-Type':'application/json; charset=utf-8',...extra}})}
function origins(env){return String(env.ALLOWED_ORIGINS||'').split(',').map(x=>x.trim().replace(/\/$/,'')).filter(Boolean)}
function cors(r, req, env) {
  const h = new Headers(r.headers);
  const origin = req.headers.get("Origin") || "";

  const allowed =
    origin === "https://artmug-portfolio.pages.dev" ||
    /^https:\/\/[a-z0-9-]+\.artmug-portfolio\.pages\.dev$/i.test(origin);

  if (allowed) {
    h.set("Access-Control-Allow-Origin", origin);
    h.set("Access-Control-Allow-Credentials", "true");
  }

  h.set("Access-Control-Allow-Headers", "Content-Type, Authorization");
  h.set("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, OPTIONS");
  h.set("Vary", "Origin");

  return new Response(r.body, {
    status: r.status,
    statusText: r.statusText,
    headers: h
  });
}
function b64u(bytes){let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function unb64u(s){s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';const bin=atob(s);return Uint8Array.from(bin,c=>c.charCodeAt(0))}
function random(n=32){const a=new Uint8Array(n);crypto.getRandomValues(a);return b64u(a)}
async function key(secret){const hash=await crypto.subtle.digest('SHA-256',enc.encode(secret));return crypto.subtle.importKey('raw',hash,{name:'AES-GCM'},false,['encrypt','decrypt'])}
async function seal(obj,secret){const iv=new Uint8Array(12);crypto.getRandomValues(iv);const k=await key(secret),data=enc.encode(JSON.stringify(obj));const ct=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},k,data));const out=new Uint8Array(iv.length+ct.length);out.set(iv);out.set(ct,iv.length);return b64u(out)}
async function openSeal(v,secret){const b=unb64u(v),iv=b.slice(0,12),ct=b.slice(12),k=await key(secret);return JSON.parse(dec.decode(await crypto.subtle.decrypt({name:'AES-GCM',iv},k,ct)))}
function cookie(name,value,opts=''){return `${name}=${value}; Path=/; Secure; ${opts}`}
async function passwordLogin(req,env){const body=await req.json().catch(()=>({}));const password=String(body.password||'');if(!env.ADMIN_PASSWORD||!password||password!==env.ADMIN_PASSWORD)return cors(json({error:'비밀번호가 올바르지 않습니다.'},401),req,env);const session=await seal({login:env.ADMIN_GITHUB_LOGINS||'admin',avatar:'',token:env.GITHUB_TOKEN,iat:Date.now()},env.SESSION_SECRET);return cors(new Response(JSON.stringify({ok:true}),{status:200,headers:{'Content-Type':'application/json','Set-Cookie':cookie('artmug_session',session,'HttpOnly; SameSite=None; Max-Age=604800')}}),req,env)}
async function callback(req,env){const u=new URL(req.url),state=u.searchParams.get('state'),code=u.searchParams.get('code'),got=(req.headers.get('Cookie')||'').match(/(?:^|; )oauth_state=([^;]+)/)?.[1];if(!state||!code||state!==got) return new Response('OAuth state error',{status:400});const tr=await fetch('https://github.com/login/oauth/access_token',{method:'POST',headers:{Accept:'application/json','Content-Type':'application/json'},body:JSON.stringify({client_id:env.OAUTH_CLIENT_ID,client_secret:env.OAUTH_CLIENT_SECRET,code,redirect_uri:`${u.origin}/auth/callback`})});const td=await tr.json();if(!td.access_token)throw new Error(td.error_description||'GitHub token exchange failed');const ur=await fetch('https://api.github.com/user',{headers:{Authorization:`Bearer ${td.access_token}`,Accept:'application/vnd.github+json','X-GitHub-Api-Version':API_VERSION,'User-Agent':'artmug-portfolio'}});const user=await ur.json();if(!ur.ok)throw new Error(user.message||'GitHub user lookup failed');const allowed=String(env.ADMIN_GITHUB_LOGINS||'').split(',').map(x=>x.trim().toLowerCase()).filter(Boolean);if(!allowed.includes(String(user.login).toLowerCase()))return new Response('관리자 권한이 없는 GitHub 계정입니다.',{status:403});const session=await seal({login:user.login,avatar:user.avatar_url||'',token:td.access_token,iat:Date.now()},env.SESSION_SECRET);return new Response(null,{status:302,headers:{Location:`${env.ALLOWED_ORIGINS.split(',')[0]}/admin.html`, 'Set-Cookie':cookie('artmug_session',session,'HttpOnly; SameSite=None; Max-Age=604800')}})}
function logout(req,env){return cors(new Response(JSON.stringify({ok:true}),{status:200,headers:{'Content-Type':'application/json','Set-Cookie':cookie('artmug_session','','HttpOnly; SameSite=None; Max-Age=0')}}),req,env)}
async function session(req,env){const v=(req.headers.get('Cookie')||'').match(/(?:^|; )artmug_session=([^;]+)/)?.[1];if(!v)return null;try{const s=await openSeal(v,env.SESSION_SECRET);if(Date.now()-s.iat>604800000)return null;return s}catch{return null}}
function ghHeaders(token){return {'Accept':'application/vnd.github+json','Authorization':`Bearer ${token}`,'X-GitHub-Api-Version':API_VERSION,'User-Agent':'artmug-portfolio'}}
function ghUrl(env,path){return `https://api.github.com/repos/${encodeURIComponent(env.GITHUB_OWNER)}/${encodeURIComponent(env.GITHUB_REPO)}/contents/${path.split('/').map(encodeURIComponent).join('/')}`}
async function ghGet(env,token,path){const r=await fetch(`${ghUrl(env,path)}?ref=${encodeURIComponent(env.GITHUB_BRANCH||'main')}`,{headers:ghHeaders(token)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(`GitHub ${r.status}: ${d.message||path}`);return d}
async function ghJson(env,token,path){const d=await ghGet(env,token,path);return JSON.parse(dec.decode(Uint8Array.from(atob(d.content.replace(/\n/g,'')),c=>c.charCodeAt(0))))}
async function publicJson(env,path){const r=await fetch(`https://raw.githubusercontent.com/${env.GITHUB_OWNER}/${env.GITHUB_REPO}/${env.GITHUB_BRANCH||'main'}/${path}`);if(!r.ok)throw new Error(`Public file ${r.status}: ${path}`);return r.json()}
async function ghList(env,token,path){const r=await fetch(ghUrl(env,path),{headers:ghHeaders(token)});const d=await r.json();if(!r.ok)throw new Error(`GitHub ${r.status}: ${d.message||path}`);return Array.isArray(d)?d:[]}
async function publicList(env,path){const r=await fetch(`https://api.github.com/repos/${env.GITHUB_OWNER}/${env.GITHUB_REPO}/contents/${path}?ref=${env.GITHUB_BRANCH||'main'}`,{headers:{Accept:'application/vnd.github+json','User-Agent':'artmug-public'}});if(!r.ok)return [];const d=await r.json();return Array.isArray(d)?d:[]}
function ext(p){return (p.split('.').pop()||'').toLowerCase()}
function item(file,cat,c={}){const name=file.split('/').pop();const m=name.match(/^(\d{14})-/);return{id:`file-${encodeURIComponent(file)}`,category:cat,file,originalName:name,alt:name.replace(/\.[^.]+$/,''),createdAt:m?m[1]:'',width:Number(c.displayWidth||0),height:Number(c.displayHeight||0)}}
async function listItems(env,token,cat){const s=await ghJson(env,token,SETTINGS),cats=s.portfolioCategories||[];const use=cat?[...cats.filter(c=>c.id===cat)]:cats;const out=[];for(const c of use){const fs=await ghList(env,token,`portfolio/${c.id}`).catch(()=>[]);for(const f of fs){if(f.type==='file'&&['gif','png','jpg','jpeg','webp'].includes(ext(f.path)))out.push(item(f.path,c.id,c))}}return out.sort((a,b)=>b.createdAt.localeCompare(a.createdAt))}
async function adminPortfolio(env,token){return listItems(env,token,'')}
async function publicPortfolio(u,env){const cat=u.searchParams.get('category')||'profile',page=Math.max(1,Number(u.searchParams.get('page')||1)),per=Math.min(30,Math.max(1,Number(u.searchParams.get('perPage')||30)));let all=[];try{const idx=await publicJson(env,INDEX);all=Array.isArray(idx)?idx.filter(x=>x.category===cat):[];if(!all.length)throw new Error('empty index')}catch{const s=await publicJson(env,SETTINGS),c=(s.portfolioCategories||[]).find(x=>x.id===cat)||{};const fs=await publicList(env,`portfolio/${cat}`);all=fs.filter(f=>f.type==='file'&&['gif','png','jpg','jpeg','webp'].includes(ext(f.path))).map(f=>item(f.path,cat,c))}all=all.sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));const total=all.length,tp=Math.max(1,Math.ceil(total/per)),pg=Math.min(page,tp);return json({items:all.slice((pg-1)*per,pg*per),total,page:pg,perPage:per,totalPages:tp},{headers:{'Cache-Control':'public,max-age=20,stale-while-revalidate=60'}})}
async function publicPresets(u,env){const s=await publicJson(env,SETTINGS);if(!s.presetEnabled)return json({items:[],total:0,page:1,totalPages:1});let all=await publicJson(env,PRESETS).catch(()=>[]);const cat=u.searchParams.get('category')||s.presetCategories?.[0]?.id||'';all=all.filter(x=>!cat||x.category===cat).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));const per=Math.min(30,Math.max(1,Number(u.searchParams.get('perPage')||30))),page=Math.max(1,Number(u.searchParams.get('page')||1)),tp=Math.max(1,Math.ceil(all.length/per)),pg=Math.min(page,tp);return json({items:all.slice((pg-1)*per,pg*per),total:all.length,page:pg,perPage:per,totalPages:tp})}
async function media(path,env){const r=await fetch(`https://raw.githubusercontent.com/${env.GITHUB_OWNER}/${env.GITHUB_REPO}/${env.GITHUB_BRANCH||'main'}/${path}`);if(!r.ok)return new Response('Not found',{status:404});const h=new Headers({'Cache-Control':'public,max-age=31536000,immutable'}),ct=r.headers.get('Content-Type');if(ct)h.set('Content-Type',ct);return new Response(r.body,{status:200,headers:h})}
function b64(buf){const bytes=new Uint8Array(buf);let s='';for(let i=0;i<bytes.length;i+=0x8000)s+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(s)}
function decodeB64(s){return Uint8Array.from(atob(s.replace(/\n/g,'')),c=>c.charCodeAt(0))}
async function putFile(env,token,path,bytes,message,sha){const body={message,content:b64(bytes),branch:env.GITHUB_BRANCH||'main'};if(sha)body.sha=sha;const r=await fetch(ghUrl(env,path),{method:'PUT',headers:{...ghHeaders(token),'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(`GitHub ${r.status}: ${d.message||path}`);return d}
async function saveJson(env,token,path,obj,msg){let sha;try{sha=(await ghGet(env,token,path)).sha}catch{}return putFile(env,token,path,enc.encode(JSON.stringify(obj,null,2)+'\n'),msg,sha)}
async function saveSettings(req,env,s){const body=await req.json();if(!body.settings)throw new Error('settings가 없습니다.');const clean=body.settings;delete clean.__proto__;await saveJson(env,s.token,SETTINGS,clean,'[CF-Pages-Skip] Update settings');return json({ok:true,settings:clean})}
function safeName(n){return String(n||'file').replace(/[^a-zA-Z0-9._-]/g,'_')}
function dimensions(b,e){try{if(e==='png')return {width:(b[16]<<24|b[17]<<16|b[18]<<8|b[19])>>>0,height:(b[20]<<24|b[21]<<16|b[22]<<8|b[23])>>>0};if(e==='gif')return {width:b[6]|b[7]<<8,height:b[8]|b[9]<<8};if(e==='webp'){if(String.fromCharCode(...b.slice(0,4))!=='RIFF')return null;const t=String.fromCharCode(...b.slice(12,16));if(t==='VP8X')return {width:1+(b[24]|b[25]<<8|b[26]<<16),height:1+(b[27]|b[28]<<8|b[29]<<16)};if(t==='VP8 ')return {width: b[26]|b[27]<<8,height:b[28]|b[29]<<8};return null}if(e==='jpeg'){let i=2;while(i<b.length){if(b[i]!==0xFF){i++;continue}const m=b[i+1];if([0xC0,0xC1,0xC2,0xC3,0xC5,0xC6,0xC7,0xC9,0xCA,0xCB,0xCD,0xCE,0xCF].includes(m))return {height:b[i+5]<<8|b[i+6],width:b[i+7]<<8|b[i+8]};const n=(b[i+2]<<8)|b[i+3];i+=2+n}}}catch{}return null}
async function upload(req,env,s,isPreset){const f=await req.formData(),file=f.get('file'),cat=String(f.get('category')||'');if(!(file instanceof File)||!cat)throw new Error('파일 또는 카테고리가 없습니다.');const bytes=new Uint8Array(await file.arrayBuffer());if(bytes.length>6291456)throw new Error('파일은 6MB 이하만 업로드할 수 있습니다.');const extn=ext(file.name);if(!['gif','png','jpg','jpeg','webp'].includes(extn))throw new Error('지원하지 않는 파일 형식입니다.');const stamp=new Date().toISOString().replace(/[-:TZ.]/g,'').slice(0,14);if(!isPreset){const settings=await ghJson(env,s.token,SETTINGS);const c=(settings.portfolioCategories||[]).find(x=>x.id===cat);if(!c)throw new Error('존재하지 않는 포트폴리오 카테고리입니다.');if(!(c.formats||[]).map(String).map(x=>x.toLowerCase()).includes(extn==='jpg'?'jpeg':extn))throw new Error('해당 카테고리에서 허용되지 않는 파일 형식입니다.');if(c.maxBytes&&bytes.length>Number(c.maxBytes))throw new Error('카테고리의 파일 용량 제한을 초과했습니다.');if(c.strictSize){const d=dimensions(bytes,extn);if(!d||d.width!==Number(c.uploadWidth)||d.height!==Number(c.uploadHeight))throw new Error(`이미지 크기는 정확히 ${c.uploadWidth} × ${c.uploadHeight}px여야 합니다.`)}}const name=`${stamp}-${random(6)}-${safeName(file.name)}`,path=isPreset?`preset/${cat}/${name}`:`portfolio/${cat}/${name}`;await putFile(env,s.token,path,bytes,`[CF-Pages-Skip] Upload ${isPreset?'preset':'portfolio'} ${name}`);if(isPreset){let list=await ghJson(env,s.token,PRESETS).catch(()=>[]);list.push({id:`preset-${random(8)}`,category:cat,file:path,originalName:file.name,createdAt:stamp});await saveJson(env,s.token,PRESETS,list,'[CF-Pages-Skip] Update presets')}else{let idx=await ghJson(env,s.token,INDEX).catch(()=>[]);idx.push({id:`file-${random(8)}`,category:cat,file:path,originalName:file.name,alt:file.name.replace(/\.[^.]+$/,''),createdAt:stamp});await saveJson(env,s.token,INDEX,idx,'[CF-Pages-Skip] Update portfolio index')}return json({ok:true,path})}
async function del(req,env,s,isPreset){const b=await req.json(),path=String(b.file||'');const allowed=isPreset?/^preset\/[^/]+\/[^/]+$/:/^portfolio\/[^/]+\/[^/]+$/;if(!allowed.test(path))throw new Error('허용되지 않은 경로입니다.');const d=await ghGet(env,s.token,path);const r=await fetch(ghUrl(env,path),{method:'DELETE',headers:{...ghHeaders(s.token),'Content-Type':'application/json'},body:JSON.stringify({message:`[CF-Pages-Skip] Delete ${path.split('/').pop()}`,sha:d.sha,branch:env.GITHUB_BRANCH||'main'})});if(!r.ok)throw new Error(`GitHub ${r.status}`);if(isPreset){let x=await ghJson(env,s.token,PRESETS).catch(()=>[]);x=x.filter(v=>v.file!==path);await saveJson(env,s.token,PRESETS,x,'[CF-Pages-Skip] Update presets')}else{let x=await ghJson(env,s.token,INDEX).catch(()=>[]);x=x.filter(v=>v.file!==path);await saveJson(env,s.token,INDEX,x,'[CF-Pages-Skip] Update portfolio index')}return json({ok:true})}

async function siteImage(req,env,s){const f=await req.formData(),file=f.get('file'),kind=String(f.get('kind')||'');if(!(file instanceof File)||!['about','comparison-a','comparison-b'].includes(kind))throw new Error('이미지 정보가 올바르지 않습니다.');const bytes=new Uint8Array(await file.arrayBuffer());if(bytes.length>6291456)throw new Error('이미지는 6MB 이하만 업로드할 수 있습니다.');const e=ext(file.name);if(!['png','jpg','jpeg','gif','webp'].includes(e))throw new Error('지원하지 않는 이미지입니다.');const name=`${Date.now()}-${random(5)}-${safeName(file.name)}`,path=`site-assets/${kind}/${name}`;await putFile(env,s.token,path,bytes,`[CF-Pages-Skip] Upload ${kind}`);const settings=await ghJson(env,s.token,SETTINGS);const key=kind==='about'?'aboutImage':kind==='comparison-a'?'comparisonAImage':'comparisonBImage';settings[key]=path;await saveJson(env,s.token,SETTINGS,settings,'[CF-Pages-Skip] Update site image');return json({ok:true,path,settings})}
async function siteImageDelete(req,env,s){const b=await req.json(),kind=String(b.kind||'');if(!['about','comparison-a','comparison-b'].includes(kind))throw new Error('잘못된 이미지 종류입니다.');const settings=await ghJson(env,s.token,SETTINGS),key=kind==='about'?'aboutImage':kind==='comparison-a'?'comparisonAImage':'comparisonBImage';const old=settings[key];settings[key]='';if(old){try{const d=await ghGet(env,s.token,old);await fetch(ghUrl(env,old),{method:'DELETE',headers:{...ghHeaders(s.token),'Content-Type':'application/json'},body:JSON.stringify({message:`[CF-Pages-Skip] Delete site image`,sha:d.sha,branch:env.GITHUB_BRANCH||'main'})})}catch{}}await saveJson(env,s.token,SETTINGS,settings,'[CF-Pages-Skip] Remove site image');return json({ok:true,settings})}
